! COMMENT BEFORE
PROGRAM EXAMPLE  ! INLINE, NO QUOTES

    ! THAT WAS A BLANK LINE; THIS IS A WHOLE-LINE COMMENT.
    IMPLICIT NONE  ! INLINE WITH 'QUOTES'
    REAL A  ! INLINE WITH ONE'QUOTE
    REAL B  ! SAME THING WITH ONE"DOUBLE QUOTE
    REAL C  ! SAME THING WITH TWO"DOUBLE"QUOTES
    PRINT *, 'ESCAPE A''INT POSSIBLE!'
    PRINT *, "ESCAPE A""INT POSSIBLE!"
    PRINT *, "ESCAPE A\'INT POSSIBLE!"
    PRINT *, 'ESCAPE A\"INT POSSIBLE!'
    PRINT *, 'ESCAPE A''INT POSSIBLE!'  ! commented
    PRINT *, "ESCAPE A""INT POSSIBLE!"  ! commented
    PRINT *, "ESCAPE A\'INT POSSIBLE!"  ! commented
    PRINT *, 'ESCAPE A\"INT POSSIBLE!'  ! commented
    PRINT *, "ESCAPE A'INT POSSIBLE!"
    PRINT *, 'ESCAPE A"INT POSSIBLE!'
    PRINT *, "ESCAPE A'INT POSSIBLE!"  ! commented
    PRINT *, 'ESCAPE A"INT POSSIBLE!'  ! commented
    PRINT *, 'ESCAPE A"INT POSSIBLE!'  ! so ! many ! comments
    PRINT *, 'ESCAPE A"INT POSSIBLE!'  ! an'd ! wit"h ! 'quotes'

END PROGRAM EXAMPLE
! COMMENT AFTER
