PROGRAM EXAMPLE
    IMPLICIT NONE
    REAL A
    REAL B
    REAL C
    PRINT *, 'ESCAPE A''INT POSSIBLE!'
    PRINT *, "ESCAPE A""INT POSSIBLE!"
    PRINT *, "ESCAPE A\'INT POSSIBLE!"
    PRINT *, 'ESCAPE A\"INT POSSIBLE!'
    PRINT *, 'ESCAPE A''INT POSSIBLE!'
    PRINT *, "ESCAPE A""INT POSSIBLE!"
    PRINT *, "ESCAPE A\'INT POSSIBLE!"
    PRINT *, 'ESCAPE A\"INT POSSIBLE!'
    PRINT *, "ESCAPE A'INT POSSIBLE!"
    PRINT *, 'ESCAPE A"INT POSSIBLE!'
    PRINT *, "ESCAPE A'INT POSSIBLE!"
    PRINT *, 'ESCAPE A"INT POSSIBLE!'
    PRINT *, 'ESCAPE A"INT POSSIBLE!'
    PRINT *, 'ESCAPE A"INT POSSIBLE!'
END PROGRAM EXAMPLE
